---
title: "15.1 Speed Dating (LMT)"
author: "Jekaterīna Butkeviča"
date: "`r Sys.Date()`"
output: word_document
---


## Uzdevums

Sameklējiet kādu lielu datu kopu (piemēram, tīmekļa servera žurnālu par pietiekami ilgu laika periodu). Izmantojot jebkādus Jums pieejamus līdzekļus (Excel tabulas, savas vai svešas programmas utml.), "izrociet" no šiem datiem kādu modeli vai šablonu. Raksturojiet savus atradumus no šajā kursā apgūtās teorijas viedokļa.


## Dati

Darbs ar pārāk lielām datu kopām man bieži beidzas ar operatīvās atmiņas pārpildījumu. Tāpēc šajā uzdevumā es izvēlējos izmantot iepazīšanās (speed dating) eksperimenta datu kopu [avots](https://www.openml.org/search?type=data&status=active&id=40536), kas satur 8379 rindas jeb tikšanās. Dati tika ievākti laika posmā no 2002. līdz 2004. gadam Kolumbijas Biznesa skolā. Eksperimenta laikā dalībnieki piedalījās četrminūšu tikšanās reizēs ar katru pretējā dzimuma dalībnieku un pēc katras tikšanās pieņēma lēmumu, vai vēlētos ar šo personu satikties atkārtoti.

Datu kopa ietver gan dalībnieku demogrāfisko informāciju, gan viņu pašvērtējumu, partneru vērtējumus un priekšstatus par to, kādas īpašības ir svarīgas potenciālajam partnerim. Papildus ir iekļauta informācija par interesēm un dzīvesveidu. Galvenais iznākuma mainīgais ir savstarpējas izvēles jeb “match” esamība, kas ļauj analizēt faktorus, kuri ietekmē lēmumu par turpmāku iepazīšanos.


## Uzdotais jautājums

Es vēlos noteikt, kuri no datu kopā aprakstītajiem faktoriem visvairāk ietekmē to, vai cilvēki vēlēsies satikties vēlreiz, t.i., vai randiņš beigsies ar “match” novērtējumu.


## Datu sagatavošana

Sākumā es nedaudz samazinu kolonnu skaitu, izņemot vairākas kolonnas par interesēm, jo rindu skaits, manuprāt, nav tik liels, lai vēl vairāk atšķaidīt datus.

```{r dati}
library(foreign)
data <- read.arff("speeddating.arff")
colnames(data)

# Izvēlamies būtiskākās kolonnas (lai nesarežģītu modeli)
df_subset <- data[, c("gender", "age", "d_age", "samerace", "importance_same_race",
                  "field", "pref_o_attractive", "pref_o_sincere", 
                  "pref_o_intelligence", "pref_o_funny", "pref_o_ambitious",
                  "pref_o_shared_interests", "attractive_o", "sinsere_o",
                  "intelligence_o", "funny_o", "ambitous_o", "shared_interests_o",
                  "d_attractive_o", "d_sinsere_o", "d_intelligence_o", 
                  "d_funny_o", "d_ambitous_o", "d_shared_interests_o", 
                  "attractive_important", "sincere_important", "intellicence_important",
                  "funny_important", "ambtition_important", "shared_interests_important",
                  "d_attractive_important", "d_sincere_important", 
                  "d_intellicence_important", "d_funny_important", "d_ambtition_important",
                  "d_shared_interests_important", "attractive", "sincere", "intelligence",
                  "funny", "ambition", "d_attractive", "d_sincere", "d_intelligence",
                  "d_funny", "d_ambition", "attractive_partner", "sincere_partner",
                  "intelligence_partner", "funny_partner", "ambition_partner",
                  "shared_interests_partner", "d_attractive_partner", "d_sincere_partner",
                  "d_intelligence_partner", "d_funny_partner", "d_ambition_partner",
                  "d_shared_interests_partner", "like", "guess_prob_liked", "d_like",
                  "d_guess_prob_liked", "met", "match")]

write.arff(df_subset, file = "speeddating_short.arff")
```

## Izmantotās metodes

Es izvēlējos LMT (Logistic Model Tree) algoritmu, jo LMT koka galos tiek veidoti loģistiskās regresijas modeļi, kas ļauj kvantitatīvi novērtēt katra skaidrojošā mainīgā ietekmi uz varbūtību iegūt “match”. Vienlaikus koka struktūra ļauj identificēt dalībnieku apakšgrupas, kurās noteiktu faktoru ietekme var atšķirties.

## Rezultāti

Rezultātā tika iegūts koks ar vienu lapu: `Number of Leaves = 1, Size of the Tree = 1`, kas nozīmē, ka dati netika sadalīti apakšgrupās, un viens lineārs modelis jau spēj pietiekami labi klasificēt datus. Papildu koka zari klasifikācijas precizitāti būtiski neuzlabo, tādēļ optimālais risinājums ir viens globāls loģistiskās regresijas modelis, jo faktoru ietekme uz “match” varbūtību ir līdzīga visai izlasei.

Krosvalidācijā ar 10 foldiem tika iegūts šāds modeļa precizitātes novērtējums:

```

Time taken to build model: 13.82 seconds

=== Stratified cross-validation ===
=== Summary ===

Correctly Classified Instances        7189               85.8081 %
Incorrectly Classified Instances      1189               14.1919 %
Kappa statistic                          0.3536
Mean absolute error                      0.2037
Root mean squared error                  0.3198
Relative absolute error                 73.9946 %
Root relative squared error             86.2293 %
Total Number of Instances             8378     

=== Detailed Accuracy By Class ===

                 TP Rate  FP Rate  Precision  Recall   F-Measure  MCC      ROC Area  PRC Area  Class
                 0,965    0,683    0,878      0,965    0,919      0,382    0,847     0,963     0
                 0,317    0,035    0,639      0,317    0,424      0,382    0,847     0,531     1
Weighted Avg.    0,858    0,576    0,838      0,858    0,838      0,382    0,847     0,892     

=== Confusion Matrix ===

    a    b   <-- classified as
 6751  247 |    a = 0
  942  438 |    b = 1
```
Kopumā modeļa precizitāte ir salīdzinoši augsta – 85,8 %, tomēr Kappa statistika (0,354) norāda, ka daļa pareizo klasifikāciju ir saistīta ar klases disbalansu, jo klase 0 dominē. Modelis ļoti labi atpazīst gadījumus, kad “match” nenotiek, taču tikai aptuveni 32 % no īstajiem “match” gadījumiem tiek pareizi klasificēti. Tas, manuprāt, nav pavisam slikti – labāk neuzzināt, ka kādam patīci, nekā domāt, ka patīci, bet patiesībā tā nav. Tāpēc situācija, kad modelis ir piesardzīgs un bieži izvēlas “nav match”, taču, ja tas prognozē “match”, tas bieži ir pareizi (salīdzinoši augsta precision), ir pieņemama.


Varbūtību iegūt “match” pozitīvi ietekmē partnera vērtējums par respondentu: `attractive_o` (+0,13), `funny_o` (+0,14) un `shared_interests_o` (+0,02). Jo augstāk partneris novērtē respondenta pievilcību, humora izjūtu un kopīgās intereses randiņa laikā, jo lielāka ir iespēja, ka randiņš beigsies ar “match”. Tas uzsver partnera subjektīvās uztveres nozīmi kā vienu no galvenajiem iznākuma noteicējiem. Arī subjektīvā simpātija un uztvertā savstarpējā interese pozitīvi ietekmē “match” varbūtību: `like` (+0,12), `guess_prob_liked` (+0,09) un `d_like` [6–8] (+0,26). Ja respondents izjūt simpātijas pret partneri un uzskata, ka tās ir savstarpējas, “match” varbūtība būtiski palielinās. Līdzībai starp partneriem ir nozīme – pozitīva ietekme novērota, ja atšķirības ir nelielas: `d_intelligence_o` [0–5] (+0,21), `d_shared_interests_o` [0–5] (+0,25), `d_funny_partner` [0–5] (+0,22) un `d_shared_interests_partner` [0–5] (+0,11). 

Savukārt negatīvu ietekmi uz “match” varbūtību rada vecuma starpība un sociālie uzskati: `d_age` (–0,01) un `importance_same_race` (–0,02). Lielāka vecuma starpība un augstāka nozīme, ko respondents piešķir rasu līdzībai, nedaudz samazina “match” iespēju. Negatīvi ietekmē arī ievērojamas atšķirības starp partneriem: piemēram, `d_funny_o` [9–10] (–0,10) un `d_intelligence_partner` [0–5] (–0,15).

Mainīgajam `met`, kas raksturo, vai partneri bija satikušies iepriekš, ir neliela pozitīva ietekme uz “match” varbūtību (β = +0,11). Tomēr šī ietekme ir salīdzinoši vāja un to var uzskatīt par sekundāru salīdzinājumā ar partnera subjektīvo vērtējumu un savstarpējo simpatiju.


LMT modeļa rezultāti liecina, ka galvenie faktori, kas nosaka, vai randiņš beigsies ar “match”, ir partnera subjektīvais vērtējums par respondentu randiņa laikā – īpaši pievilcība, humors un kopīgās intereses – kā arī respondenta paša uztvertā savstarpējā patika. Deklarētās preferences un demogrāfiskie faktori spēlē sekundāru lomu, savukārt lielāka saskaņa starp partneriem palielina “match” varbūtību.


Pieliku arī uzģenerēto koku:

Number of Leaves : 1 
Size of the Tree : 1 

LM_1: 

Class 0 : 
4.79 + [d_age] * 0.01 + 
[importance_same_race] * 0.02 + 
[field=Art History/medicine] * -0.9 + 
[field=Biochemistry & Molecular Biophysics] * -0.59 + 
[field=Biology] * -0.41 + 
[field=Business] * -0.18 + 
[field=Business [MBA]] * -0.43 + 
[field=Classics] * -0.73 + 
[field=Climate Dynamics] * -0.64 + 
[field=Clinical Psychology] * -0.38 + 
[field=Communications] * -0.63 + 
[field=Financial Engineering] * -0.49 + 
[field=General management/finance] * -0.74 + 
[field=German Literature] * -1.06 + 
[field=GS Postbacc PreMed] * -0.49 + 
[field=Higher Ed. - M.A.] * -0.86 + 
[field=International Educational Development] * -0.56 + 
[field=International Relations] * -0.62 + 
[field=law] * -0.25 + 
[field=Law/Business] * -0.71 + 
[field=MA Science Education] * -0.77 + 
[field=Masters in Public Administration] * -1.13 + 
[field=math] * -0.91 + 
[field=medicine] * -0.95 + 
[field=Medicine] * 0.4 + 
[field=Microbiology] * 0.48 + 
[field=money] * -0.79 + 
[field=Neurobiology] * -0.61 + 
[field=Neuroscience] * 0.74 + 
[field=Organizational Psychology] * -0.53 + 
[field=physics] * -0.58 + 
[field=Polish] * -1.09 + 
[field=Religion] * -0.54 + 
[field=Sociomedical Sciences- School of Public Health] * -1.02 +
[pref_o_intelligence] * -0.01 + 
[pref_o_ambitious] * 0.01 + 
[attractive_o] * -0.13 + 
[funny_o] * -0.14 + 
[ambitous_o] * 0.05 + 
[shared_interests_o] * -0.02 + 
[d_attractive_o=[6-8]] * -0.18 + 
[d_intelligence_o=[0-5]] * 0.21 + 
[d_funny_o=[9-10]] * 0.1 + 
[d_shared_interests_o=[0-5]] * 0.25 + 
[d_intellicence_important=[21-100]] * -0.14 + 
[d_attractive=[0-5]] * -0.17 + 
[d_intelligence=[9-10]] * 0.09 + 
[d_funny=[9-10]] * 0.07 + 
[attractive_partner] * -0.12 + 
[funny_partner] * -0.02 + 
[ambition_partner] * 0.03 + 
[d_attractive_partner=[6-8]] * -0.1 + 
[d_intelligence_partner=[0-5]] * 0.15 + 
[d_funny_partner=[0-5]] * 0.22 + 
[d_shared_interests_partner=[0-5]] * 0.11 + 
[like] * -0.12 + 
[guess_prob_liked] * -0.09 + 
[d_like=[6-8]] * -0.26 + 
[met] * -0.11 

Class 1 : 
-4.79 + [d_age] * -0.01 + 
[importance_same_race] * -0.02 + 
[field=Art History/medicine] * 0.9 + 
[field=Biochemistry & Molecular Biophysics] * 0.59 + 
[field=Biology] * 0.41 + 
[field=Business] * 0.18 + 
[field=Business [MBA]] * 0.43 + 
[field=Classics] * 0.73 + 
[field=Climate Dynamics] * 0.64 + 
[field=Clinical Psychology] * 0.38 + 
[field=Communications] * 0.63 + 
[field=Financial Engineering] * 0.49 + 
[field=General management/finance] * 0.74 + 
[field=German Literature] * 1.06 + 
[field=GS Postbacc PreMed] * 0.49 + 
[field=Higher Ed. - M.A.] * 0.86 + 
[field=International Educational Development] * 0.56 + 
[field=International Relations] * 0.62 + 
[field=law] * 0.25 + 
[field=Law/Business] * 0.71 + 
[field=MA Science Education] * 0.77 + 
[field=Masters in Public Administration] * 1.13 + 
[field=math] * 0.91 + 
[field=medicine] * 0.95 + 
[field=Medicine] * -0.4 + 
[field=Microbiology] * -0.48 + 
[field=money] * 0.79 + 
[field=Neurobiology] * 0.61 + 
[field=Neuroscience] * -0.74 + 
[field=Organizational Psychology] * 0.53 + 
[field=physics] * 0.58 + 
[field=Polish] * 1.09 +
[field=Religion] * 0.54 + 
[field=Sociomedical Sciences- School of Public Health] * 1.02 + 
[pref_o_intelligence] * 0.01 + 
[pref_o_ambitious] * -0.01 + 
[attractive_o] * 0.13 + 
[funny_o] * 0.14 + 
[ambitous_o] * -0.05 + 
[shared_interests_o] * 0.02 + 
[d_attractive_o=[6-8]] * 0.18 + 
[d_intelligence_o=[0-5]] * -0.21 + 
[d_funny_o=[9-10]] * -0.1 +
[d_shared_interests_o=[0-5]] * -0.25 + 
[d_intellicence_important=[21-100]] * 0.14 + 
[d_attractive=[0-5]] * 0.17 + 
[d_intelligence=[9-10]] * -0.09 + 
[d_funny=[9-10]] * -0.07 + 
[attractive_partner] * 0.12 + 
[funny_partner] * 0.02 + 
[ambition_partner] * -0.03 + 
[d_attractive_partner=[6-8]] * 0.1 + 
[d_intelligence_partner=[0-5]] * -0.15 + 
[d_funny_partner=[0-5]] * -0.22 + 
[d_shared_interests_partner=[0-5]] * -0.11 + 
[like] * 0.12 + 
[guess_prob_liked] * 0.09 + 
[d_like=[6-8]] * 0.26 + 
[met] * 0.11
